services:
  postgres:
    image: 'postgres:15'
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: doa_store
      POSTGRES_USER: doa_user
      POSTGRES_PASSWORD: doa_password

    ports:
      - '55432:5432'

    volumes:
      - doa-db-data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U doa_user -d doa_store" ]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  doa-db-data: